config/routes.rb
BeerTracker::Application.routes.draw do
  devise_for :users

  resources :beers

  get "profile/index"
  get "profile/add_tried_from_list"
  get "profile/add_tried_by_new"
  post "profile/create_tried"
  post "profile/create_beer_and_tried"

  root :to => "profile#index"
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  @@generic_picture = 'generic_beer.png'

  attr_accessible :bottle, :brew, :brewery, :can, :picture, :users

  has_many :trieds, :dependent => :destroy
  has_many :users, :through => :trieds

  def get_picture_or_generic_if_none
    return @@generic_picture if self.picture == "" || self.picture == nil
    
    self.picture
  end
end

app/models/tried.rb
class Tried < ActiveRecord::Base
  belongs_to :user
  belongs_to :beer

  def get_beer
    Beer.find(self.beer_id)
  end

  def self.create_from_ids_and_rating user_id, beer_id, rating
    tried = Tried.new

    tried.user_id = user_id
    tried.beer_id = beer_id
    tried.rating = rating

    tried.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :beers
  # attr_accessible :title, :body

  def get_username
    at_sign_location = self.email.index("@")
    self.email[0..at_sign_location-1]
  end

  has_many :trieds, :dependent => :destroy
  has_many :beers, :through => :trieds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_filter :authenticate_user!

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beers }
    end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @beer = Beer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer }
    end
  end

  # GET /beers/new
  # GET /beers/new.json
  def new
    @beer = Beer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beer }
    end
  end

  # GET /beers/1/edit
  def edit
    @beer = Beer.find(params[:id])
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(params[:beer])

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render json: @beer, status: :created, location: @beer }
      else
        format.html { render action: "new" }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beers/1
  # PUT /beers/1.json
  def update
    @beer = Beer.find(params[:id])

    respond_to do |format|
      if current_user.is_admin?
        if @beer.update_attributes(params[:beer])
          format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @beer.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @beer, notice: 'Unprocessable' }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy

    if current_user.is_admin?
      @beer = Beer.find(params[:id])
      @beer.destroy
    end

    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  before_filter :authenticate_user!

  def index
  end

  def add_tried_from_list
    @beers = Beer.all
  end

  def add_tried_by_new
    @beer = Beer.new
    @tried = Tried.new
  end

  def create_tried
    Tried.create_from_ids_and_rating current_user.id,
                                     params[:beer_id],
                                     params[:rating]

    redirect_to profile_index_path
  end

  def create_beer_and_tried
    @beer = Beer.new(params[:beer])

    if @beer.save
      Tried.create_from_ids_and_rating current_user.id, 
                                       @beer.id,
                                       params[:rating]
    end

    redirect_to profile_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Listing beers</h1>

<%= render '/profile/filter_brewery'%>

<%= render '/profile/system_filterable_form'%>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @beer.brewery %> ~ <%= @beer.brew %>
<p>
  <%= image_tag @beer.get_picture_or_generic_if_none %>
</p>


<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerTracker</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body style="margin-right:10%; margin-left:10%;">

  <div class="banner">
    <h2>Beer Tracker (Beta)</h2>
    <p>"For the beer connoisseur"</p>
    <table style="width:100%;border: 1px solid black;">
      <tr>
        <td><%= link_to "My Profile", profile_index_path %></td>
        <td><%= link_to "View Beers", beers_path %></td>
        <td><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></td>
      <tr>
    </table>
  </div>

  <% if params[:controller].include? "devise"%>
  <p class="notice" style="color:green;"><%= notice %></p>
  <p class="alert" style="color:red;"><%= alert %></p>
  <% end %>

  <%= yield %>

  </body>
</html>